const PROPERTIES = [
  {
    id: "the-alderton",
    name: "The Alderton",
    tagline: "Penthouse Living Redefined",
    type: "Luxury Penthouse Collection",
    status: "Now Selling",
    location: "Upper East Side, New York",
    address: "895 Fifth Avenue, NY 10021",
    price: "From $4.2M",
    priceRaw: "$4.2M",
    completion: "Q3 2025",
    storeys: 62,
    units: 48,
    available: 15,
    availablePct: 31,
    architect: "BIG — Bjarke Ingels Group",
    interiors: "David Collins Studio",
    heroImg: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80", label: "Building Facade" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room — Penthouse 48A" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&q=80", label: "Primary Suite" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&q=75", label: "Terrace" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&q=75", label: "Exterior Detail" },
    ],
    description: [
      "The Alderton presents 48 meticulously designed penthouse residences atop a landmark tower on Fifth Avenue. Each home features floor-to-ceiling glazing, private terraces with panoramic Central Park views, and interiors crafted by the David Collins Studio.",
      "Rising 62 storeys above the Upper East Side, The Alderton represents the culmination of Meridian's design philosophy: uncompromising architecture that engages its setting while creating homes of lasting beauty and value.",
      "Residents enter through a private porte-cochère into a double-height lobby of book-matched Calacatta marble. The building's amenity programme spans 28,000 sq ft across four dedicated levels."
    ],
    highlights: [{ num: "48", label: "Total Residences" }, { num: "62", label: "Storeys" }, { num: "15", label: "Available Now" }],
    floorPlans: [
      { key: "two-bed", label: "Two Bedroom", floors: "Floors 18–38", interior: "2,840 ft²", terrace: "680 ft²", beds: "2", baths: "2.5", price: "$4.2M", available: "5 Units", inclusions: ["Calacatta marble flooring throughout", "Custom David Collins Studio cabinetry", "Gaggenau appliance suite", "Floor-to-ceiling triple-glazed curtain wall", "Private terrace with outdoor kitchen"] },
      { key: "three-bed", label: "Three Bedroom", floors: "Floors 39–52", interior: "3,920 ft²", terrace: "940 ft²", beds: "3", baths: "3.5", price: "$7.8M", available: "6 Units", inclusions: ["Honed Statuario marble throughout", "Full David Collins Studio interior", "Private study with custom shelving", "Smart home — Crestron platform", "Dedicated laundry and staff entrance"] },
      { key: "four-bed", label: "Four Bedroom", floors: "Floors 53–60", interior: "5,600 ft²", terrace: "1,240 ft²", beds: "4", baths: "4.5", price: "$14.5M", available: "3 Units", inclusions: ["Bespoke stone selection", "Private wine room with climate control", "Staff suite with separate entrance", "4-car underground parking", "Priority concierge services"] },
      { key: "penthouse", label: "Full-Floor Penthouse", floors: "Floors 61–62", interior: "8,200 ft²", terrace: "2,100 ft²", beds: "5", baths: "6", price: "POA", available: "1 of 2", inclusions: ["Fully bespoke David Collins interior", "Private rooftop pool and terrace", "Dedicated elevator lobby", "6-car private garage with EV charging", "24/7 house manager and concierge"] }
    ],
    amenities: [
      { icon: "◈", title: "Residents' Club", desc: "A 6,000 sq ft private members' lounge with dining room, cocktail bar, and wine cellar." },
      { icon: "◆", title: "Fitness & Wellness", desc: "Full-floor wellness centre with 75-foot lap pool, hot tub, sauna suite, and treatment rooms." },
      { icon: "✦", title: "Private Dining", desc: "Resident-only private dining room with in-house culinary team for private events." },
      { icon: "▲", title: "Screening Room", desc: "40-seat private cinema with Dolby Atmos sound, available for resident bookings seven days a week." },
      { icon: "●", title: "Children's Suite", desc: "Dedicated children's programme room, playroom, and supervised after-school services." },
      { icon: "◉", title: "Sky Terrace", desc: "Residents' rooftop terrace on the 61st floor with 360° views of Central Park and the skyline." },
      { icon: "◈", title: "Concierge Services", desc: "White-glove 24/7 concierge team for travel, restaurants, household services, and all requests." },
      { icon: "◆", title: "Valet Parking", desc: "Full-service valet with EV charging. Private garage allocations for penthouse residences." },
    ],
    architect_quote: "The Alderton is a building that speaks in a quiet voice — confident in its restraint, extraordinary in its precision. Every line is deliberate.",
    architect_name: "Bjarke Ingels — BIG",
    designTeam: [
      { role: "Architecture", name: "BIG — Bjarke Ingels Group", firm: "Copenhagen / New York / London", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "David Collins Studio", firm: "London / New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Structural Engineering", name: "Thornton Tomasetti", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Parks & Recreation", items: [{ name: "Central Park — 72nd St Entrance", dist: "2", unit: "min walk" }, { name: "The Reservoir", dist: "5", unit: "min walk" }, { name: "Carl Schurz Park", dist: "12", unit: "min walk" }] },
      { cat: "Culture & Dining", items: [{ name: "The Metropolitan Museum of Art", dist: "4", unit: "min walk" }, { name: "Café Boulud", dist: "2", unit: "min walk" }, { name: "The Carlyle Hotel", dist: "3", unit: "min walk" }] },
      { cat: "Transportation", items: [{ name: "4/5/6 Subway — 77th Street", dist: "3", unit: "min walk" }, { name: "JFK Airport", dist: "35", unit: "min drive" }, { name: "Teterboro Airport (TEB)", dist: "22", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "The quality of craftsmanship at The Alderton surpassed anything I'd seen at this price point in New York. The stone alone looks like it was designed by a sculptor, not a contractor.", name: "James & Catherine Whitmore", unit: "Penthouse 48A · Purchased 2024" },
      { text: "From the first viewing through to completion, Meridian's sales team was exceptional. Everything they promised, they delivered — on time, without compromise.", name: "Dr. Aisha Okonkwo", unit: "Residence 3402 · Purchased 2024" },
      { text: "We've lived in luxury buildings across three continents. The Alderton is categorically different — the attention to service and the building's community feel are genuinely rare.", name: "Marcus & Helena Lindqvist", unit: "Residence 5601 · Purchased 2024" },
    ],
  },
  {
    id: "one-meridian",
    name: "One Meridian",
    tagline: "A New Icon for Tribeca",
    type: "Luxury Condominium",
    status: "Pre-Sale",
    location: "Tribeca, New York",
    address: "1 Hudson Square, NY 10013",
    price: "From $3.1M",
    priceRaw: "$3.1M",
    completion: "Q2 2027",
    storeys: 44,
    units: 62,
    available: 62,
    availablePct: 100,
    architect: "Zaha Hadid Architects",
    interiors: "Yabu Pushelberg",
    heroImg: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80", label: "Building Render" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=700&q=80", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Primary Suite" },
      { src: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&q=75", label: "Terrace" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&q=75", label: "Facade Detail" },
    ],
    description: [
      "One Meridian rises 44 storeys above Hudson Square, bringing Zaha Hadid's signature fluid forms to one of Lower Manhattan's most exciting emerging neighbourhoods. 62 residences across one of the city's most distinctive new towers.",
      "Interiors by Yabu Pushelberg bring a warmth and tactility to Hadid's dramatic exterior — curved ceilings, bespoke stone, and floor-to-ceiling glazing frame uninterrupted Hudson River views from every residence.",
      "Now registering interest for pre-sale. Expected completion Q2 2027."
    ],
    highlights: [{ num: "62", label: "Total Residences" }, { num: "44", label: "Storeys" }, { num: "62", label: "Pre-Sale Now" }],
    floorPlans: [
      { key: "one-bed", label: "One Bedroom", floors: "Floors 8–22", interior: "1,240 ft²", terrace: "280 ft²", beds: "1", baths: "1.5", price: "$3.1M", available: "18 Units", inclusions: ["Fluid curved ceiling profiles", "Yabu Pushelberg bespoke millwork", "Gaggenau kitchen suite", "Floor-to-ceiling river-facing glazing", "Private terrace on select floors"] },
      { key: "two-bed", label: "Two Bedroom", floors: "Floors 23–36", interior: "2,180 ft²", terrace: "460 ft²", beds: "2", baths: "2.5", price: "$5.4M", available: "24 Units", inclusions: ["Honed marble throughout", "Custom Yabu Pushelberg interiors", "Hudson River panoramic views", "Smart home automation", "Private outdoor terrace"] },
      { key: "three-bed", label: "Three Bedroom", floors: "Floors 37–42", interior: "3,600 ft²", terrace: "820 ft²", beds: "3", baths: "3.5", price: "$9.8M", available: "16 Units", inclusions: ["Bespoke stone selection consultation", "Full Yabu Pushelberg package", "Private study and wine storage", "Dedicated laundry suite", "Wrap-around terrace"] },
      { key: "penthouse", label: "Penthouse", floors: "Floors 43–44", interior: "6,800 ft²", terrace: "1,600 ft²", beds: "4", baths: "5", price: "POA", available: "4 Units", inclusions: ["Fully bespoke Yabu Pushelberg interior", "Wrap-around terrace with city views", "Private elevator vestibule", "4-car parking allocation", "Dedicated concierge services"] }
    ],
    amenities: [
      { icon: "◈", title: "Residents' Lounge", desc: "A 4,500 sq ft private lounge and dining room with Hudson River views." },
      { icon: "◆", title: "Fitness Centre", desc: "State-of-the-art gym, 60-foot pool, sauna, and yoga studio." },
      { icon: "✦", title: "Rooftop Terrace", desc: "Landscaped residents' terrace on the 43rd floor with panoramic city views." },
      { icon: "▲", title: "Co-Working Lounge", desc: "Private work suites and meeting rooms for resident use, 24/7." },
      { icon: "●", title: "Children's Room", desc: "Dedicated playroom and after-school programme space for resident families." },
      { icon: "◉", title: "Concierge", desc: "24/7 front-of-house concierge and building management team." },
    ],
    architect_quote: "One Meridian is an expression of movement frozen in stone and glass — a building that appears to grow organically from the Hudson waterfront.",
    architect_name: "Patrik Schumacher — Zaha Hadid Architects",
    designTeam: [
      { role: "Architecture", name: "Zaha Hadid Architects", firm: "London / New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Yabu Pushelberg", firm: "New York / Toronto", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Structural Engineering", name: "Arup", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Neighbourhood", items: [{ name: "Hudson River Park", dist: "2", unit: "min walk" }, { name: "The High Line", dist: "8", unit: "min walk" }, { name: "Washington Market Park", dist: "4", unit: "min walk" }] },
      { cat: "Culture & Dining", items: [{ name: "Nobu Tribeca", dist: "4", unit: "min walk" }, { name: "Locanda Verde", dist: "5", unit: "min walk" }, { name: "The Odeon", dist: "6", unit: "min walk" }] },
      { cat: "Transportation", items: [{ name: "A/C/E Subway — Canal St", dist: "4", unit: "min walk" }, { name: "1/2/3 Subway — Chambers St", dist: "6", unit: "min walk" }, { name: "JFK Airport", dist: "40", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "Registering for One Meridian was effortless — the Meridian sales team was responsive, knowledgeable, and completely pressure-free. We're thrilled to be among the first buyers.", name: "Thomas & Eva Brennan", unit: "Residence 3201 · Registered 2024" },
    ],
  },
  {
    id: "the-carlyle-residences",
    name: "The Carlyle Residences",
    tagline: "Full-Floor Living on the Park",
    type: "Full-Floor Residences",
    status: "Now Selling",
    location: "Midtown East, New York",
    address: "35 East 76th Street, NY 10021",
    price: "From $6.8M",
    priceRaw: "$6.8M",
    completion: "Q1 2026",
    storeys: 38,
    units: 36,
    available: 9,
    availablePct: 25,
    architect: "Robert A.M. Stern Architects",
    interiors: "Alexandra Champalimaud",
    heroImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80", label: "Building Facade" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Grand Salon" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=700&q=80", label: "Primary Suite" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Chef's Kitchen" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=75", label: "Library" },
      { src: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=75", label: "Terrace" },
    ],
    description: [
      "The Carlyle Residences occupy the upper floors of one of Manhattan's most iconic addresses. Each of the 36 residences spans a full floor, offering a level of privacy and proportion rarely found in New York.",
      "Designed by Robert A.M. Stern Architects in his signature Park Avenue style, and dressed by Alexandra Champalimaud with an interior language of restrained grandeur — rich materials, classical details, and spaces designed for serious living.",
      "Only 9 residences remain. Completion expected Q1 2026."
    ],
    highlights: [{ num: "36", label: "Total Residences" }, { num: "38", label: "Storeys" }, { num: "9", label: "Available Now" }],
    floorPlans: [
      { key: "three-bed", label: "Three Bedroom", floors: "Floors 12–24", interior: "4,100 ft²", terrace: "600 ft²", beds: "3", baths: "3.5", price: "$6.8M", available: "4 Units", inclusions: ["Full-floor privacy", "Champalimaud bespoke millwork", "Library and formal dining room", "Gaggenau professional kitchen", "Private terrace"] },
      { key: "four-bed", label: "Four Bedroom", floors: "Floors 25–34", interior: "5,800 ft²", terrace: "900 ft²", beds: "4", baths: "4.5", price: "$12.4M", available: "4 Units", inclusions: ["Limestone and oak throughout", "Gallery entrance foyer", "Staff quarters with separate entry", "Private wine cellar", "Wrap terrace with Park views"] },
      { key: "penthouse", label: "Penthouse", floors: "Floors 35–38", interior: "9,200 ft²", terrace: "2,400 ft²", beds: "5+", baths: "6", price: "POA", available: "1 of 1", inclusions: ["Completely bespoke specification", "Rooftop pool and entertaining terrace", "Private elevator", "6-car garage allocation", "Permanent house manager"] }
    ],
    amenities: [
      { icon: "◈", title: "Grand Lobby", desc: "Double-height lobby of hand-laid limestone with 24/7 attended reception." },
      { icon: "◆", title: "Private Spa", desc: "Full-service spa with pool, steam room, treatment suites, and resident fitness centre." },
      { icon: "✦", title: "Members' Dining", desc: "Private dining room and chef's kitchen available for resident events." },
      { icon: "▲", title: "Terrace Gardens", desc: "Private residents' gardens at the 11th floor podium, professionally maintained." },
      { icon: "●", title: "Valet Parking", desc: "Attended valet and underground garage for all residents." },
      { icon: "◉", title: "Concierge", desc: "Round-the-clock concierge and building management at the highest standard." },
    ],
    architect_quote: "The Carlyle Residences honour the tradition of great Upper East Side architecture while setting a new benchmark for modern full-floor living.",
    architect_name: "Robert A.M. Stern Architects",
    designTeam: [
      { role: "Architecture", name: "Robert A.M. Stern Architects", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Alexandra Champalimaud", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "MPFP", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Parks & Recreation", items: [{ name: "Central Park — 76th Street", dist: "1", unit: "min walk" }, { name: "The Metropolitan Museum", dist: "3", unit: "min walk" }, { name: "The Reservoir", dist: "8", unit: "min walk" }] },
      { cat: "Culture & Dining", items: [{ name: "The Carlyle Hotel Bar", dist: "1", unit: "min walk" }, { name: "Daniel Restaurant", dist: "2", unit: "min walk" }, { name: "Mark's Restaurant", dist: "3", unit: "min walk" }] },
      { cat: "Transportation", items: [{ name: "4/5/6 Subway — 77th St", dist: "3", unit: "min walk" }, { name: "JFK Airport", dist: "38", unit: "min drive" }, { name: "Teterboro (TEB)", dist: "24", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "The Carlyle Residences represent the finest full-floor product in the city. The scale of the rooms, the quality of the finishes — it's genuinely extraordinary value at this level.", name: "William & Anne Forsythe", unit: "Residence 2801 · Purchased 2024" },
    ],
  },
  {
    id: "woodland-reserve",
    name: "Woodland Reserve",
    tagline: "The Connecticut Estate Reimagined",
    type: "Private Estate Community",
    status: "Pre-Sale",
    location: "Darien, Connecticut",
    address: "Woodland Drive, Darien, CT 06820",
    price: "From $4.4M",
    priceRaw: "$4.4M",
    completion: "Q4 2026",
    storeys: 3,
    units: 24,
    available: 24,
    availablePct: 100,
    architect: "Shigeru Ban Architects",
    interiors: "Roman and Williams",
    heroImg: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80", label: "Estate Exterior" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80", label: "Grounds" },
      { src: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=700&q=80", label: "Pool House" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=75", label: "Master Suite" },
    ],
    description: [
      "Woodland Reserve is a curated community of 24 private estate homes set within 180 acres of preserved Connecticut woodland. Each home is individually designed by Shigeru Ban Architects, with interiors by Roman and Williams.",
      "The community is gated and managed, with shared amenities including a private clubhouse, tennis courts, and miles of private walking trails. Every home occupies a minimum 3-acre private plot.",
      "Pre-sale registration now open. Completion Q4 2026."
    ],
    highlights: [{ num: "24", label: "Estate Homes" }, { num: "180", label: "Acres of Woodland" }, { num: "3+", label: "Acres Per Home" }],
    floorPlans: [
      { key: "four-bed", label: "Four Bedroom", floors: "Single-family estate home", interior: "5,200 ft²", terrace: "1,800 ft²", beds: "4", baths: "4.5", price: "$4.4M", available: "10 Homes", inclusions: ["Shigeru Ban architectural design", "Roman and Williams interiors", "Infinity pool and pool house", "3-car garage", "Private woodland plot — 3 acres"] },
      { key: "five-bed", label: "Five Bedroom", floors: "Single-family estate home", interior: "6,800 ft²", terrace: "2,400 ft²", beds: "5", baths: "5.5", price: "$6.2M", available: "10 Homes", inclusions: ["Expanded woodland setting — 4+ acres", "Guest cottage", "Home cinema and gym", "Wine cellar and tasting room", "Outdoor entertaining pavilion"] },
      { key: "grand-estate", label: "Grand Estate", floors: "Single-family estate home", interior: "9,400 ft²", terrace: "4,000+ ft²", beds: "6+", baths: "7", price: "POA", available: "4 Homes", inclusions: ["Maximum privacy — 6+ acre plot", "Full bespoke specification", "Separate guest house", "Tennis court allocation", "Live-in staff quarters"] }
    ],
    amenities: [
      { icon: "◈", title: "Private Clubhouse", desc: "A 12,000 sq ft members' clubhouse with dining, lounge, and event spaces exclusively for residents." },
      { icon: "◆", title: "Tennis & Sport", desc: "Four championship tennis courts, a padel court, and a croquet lawn." },
      { icon: "✦", title: "Walking Trails", desc: "14 miles of private, maintained woodland trails through the community's 180-acre preserve." },
      { icon: "▲", title: "Community Pool", desc: "Heated community pool and pool club, open seasonally to all residents." },
      { icon: "●", title: "Concierge", desc: "Community management team providing full concierge, security, and maintenance services." },
      { icon: "◉", title: "Gated Security", desc: "24/7 gated entry, perimeter security, and private road maintenance." },
    ],
    architect_quote: "Woodland Reserve is architecture in dialogue with nature — every home is positioned to maximise light, views, and the particular character of its woodland setting.",
    architect_name: "Shigeru Ban Architects",
    designTeam: [
      { role: "Architecture", name: "Shigeru Ban Architects", firm: "Tokyo / New York / Paris", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Roman and Williams", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "Reed Hilderbrand", firm: "Cambridge, MA", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80",
    locationPins: [
      { cat: "Community", items: [{ name: "Darien Town Centre", dist: "8", unit: "min drive" }, { name: "Tokeneke Beach", dist: "12", unit: "min drive" }, { name: "Weed Beach", dist: "10", unit: "min drive" }] },
      { cat: "Connectivity", items: [{ name: "Darien Metro-North Station", dist: "6", unit: "min drive" }, { name: "Midtown Manhattan", dist: "50", unit: "min train" }, { name: "Westchester Airport (HPN)", dist: "25", unit: "min drive" }] },
      { cat: "Schools", items: [{ name: "Darien High School", dist: "7", unit: "min drive" }, { name: "King School (Private)", dist: "15", unit: "min drive" }, { name: "Brunswick School", dist: "18", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "We've been looking for a Connecticut estate community that matches Manhattan quality for years. Woodland Reserve is it. The Shigeru Ban architecture alone is worth the investment.", name: "Robert & Claire Hammond", unit: "Registered 2024" },
    ],
  },
  {
    id: "harlow-estates",
    name: "Harlow Estates",
    tagline: "Greenwich at Its Finest",
    type: "Private Estate",
    status: "Completed",
    location: "Greenwich, Connecticut",
    address: "Harlow Lane, Greenwich, CT 06830",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2023",
    storeys: 3,
    units: 18,
    available: 0,
    availablePct: 0,
    architect: "Ferguson & Shamamian",
    interiors: "Cullman & Kravis",
    heroImg: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80", label: "Estate Facade" },
      { src: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=700&q=80", label: "Pool Terrace" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=700&q=80", label: "Gardens" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=75", label: "Primary Suite" },
    ],
    description: [
      "Harlow Estates is a collection of 18 private estate homes in the heart of Greenwich's Back Country — one of the most prestigious residential addresses in Connecticut.",
      "Designed by Ferguson & Shamamian in the American shingle style, with interiors by Cullman & Kravis, each home was built to a specification that rivals the finest private commissions in the country.",
      "Harlow Estates sold out in 2023. Resale enquiries welcomed through Meridian's secondary market programme."
    ],
    highlights: [{ num: "18", label: "Estate Homes" }, { num: "100%", label: "Sold" }, { num: "2023", label: "Completed" }],
    floorPlans: [
      { key: "estate", label: "Estate Home", floors: "Single-family, 3 storeys", interior: "7,400 ft²", terrace: "3,200 ft²", beds: "5", baths: "5.5", price: "Sold Out", available: "0 Available", inclusions: ["Ferguson & Shamamian shingle-style architecture", "Cullman & Kravis full interior specification", "Pool and pool house", "4-car garage", "Private 2.5-acre lot"] }
    ],
    amenities: [
      { icon: "◈", title: "Gated Community", desc: "Private gated entry with 24/7 security and community management." },
      { icon: "◆", title: "Tennis Courts", desc: "Three Har-Tru tennis courts shared across the community." },
      { icon: "✦", title: "Walking Trails", desc: "Six miles of private community trails through woodland and meadow." },
      { icon: "▲", title: "Concierge", desc: "Full-service community management and concierge available to all residents." },
    ],
    architect_quote: "Harlow Estates is a love letter to the great American country house — built with craft, humility, and an eye on permanence.",
    architect_name: "Ferguson & Shamamian Architects",
    designTeam: [
      { role: "Architecture", name: "Ferguson & Shamamian", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Cullman & Kravis", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "Innocenti & Webel", firm: "Locust Valley, NY", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Community", items: [{ name: "Greenwich Town Centre", dist: "12", unit: "min drive" }, { name: "Greenwich Country Club", dist: "8", unit: "min drive" }, { name: "Tod's Point Beach", dist: "15", unit: "min drive" }] },
      { cat: "Connectivity", items: [{ name: "Greenwich Metro-North", dist: "14", unit: "min drive" }, { name: "Midtown Manhattan", dist: "45", unit: "min train" }, { name: "Westchester Airport (HPN)", dist: "20", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "Harlow Estates is simply the best residential product we've ever encountered in Connecticut. The attention to detail — from the architecture to the landscaping — is extraordinary.", name: "Charles & Margaret Eliot", unit: "Estate 7 · Purchased 2022" },
    ],
  },
  {
    id: "shore-reserve",
    name: "Shore Reserve",
    tagline: "Waterfront Living Without Compromise",
    type: "Waterfront Compound",
    status: "Completed",
    location: "East Hampton, New York",
    address: "Shore Reserve Drive, East Hampton, NY 11937",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2022",
    storeys: 2,
    units: 12,
    available: 0,
    availablePct: 0,
    architect: "Gabellini Sheppard Associates",
    interiors: "Studio Sofield",
    heroImg: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80", label: "Waterfront Facade" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80", label: "Ocean Terrace" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Master Suite" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=75", label: "Pool Deck" },
    ],
    description: [
      "Shore Reserve is a collection of 12 oceanfront compounds at one of East Hampton's most coveted beachfront locations. Each property occupies a full acre of direct oceanfront land with 100 feet of private beach.",
      "Designed by Gabellini Sheppard with interiors by Studio Sofield, each home is a study in elemental luxury — honest materials, muscular architecture, and spaces that dissolve the boundary between inside and out.",
      "Shore Reserve sold out ahead of schedule in 2022. For resale enquiries, contact the Meridian team."
    ],
    highlights: [{ num: "12", label: "Oceanfront Homes" }, { num: "100ft", label: "Private Beach Each" }, { num: "2022", label: "Completed" }],
    floorPlans: [
      { key: "compound", label: "Oceanfront Compound", floors: "Single-family, 2 storeys", interior: "8,200 ft²", terrace: "4,800 ft²", beds: "5", baths: "6", price: "Sold Out", available: "Resale Enquiries Only", inclusions: ["Direct oceanfront setting — 1 acre", "Private beach access — 100 linear feet", "Infinity pool facing the ocean", "Pool house with guest suite", "5-car motor court"] }
    ],
    amenities: [
      { icon: "◈", title: "Private Beach", desc: "100 feet of private oceanfront beach for each residence." },
      { icon: "◆", title: "Community Pool Club", desc: "Shared pool club and beach facilities at the community's central oceanfront pavilion." },
      { icon: "✦", title: "Gated Security", desc: "24/7 gated entry and private road maintenance." },
      { icon: "▲", title: "Concierge", desc: "Seasonal community management and concierge services." },
    ],
    architect_quote: "Shore Reserve required architecture that didn't compete with the ocean — but framed it, honoured it, and made it the centrepiece of every room.",
    architect_name: "Michael Gabellini — Gabellini Sheppard Associates",
    designTeam: [
      { role: "Architecture", name: "Gabellini Sheppard Associates", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Studio Sofield", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "Edmund Hollander Design", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=900&q=80",
    locationPins: [
      { cat: "Hamptons", items: [{ name: "East Hampton Village", dist: "8", unit: "min drive" }, { name: "Main Beach", dist: "10", unit: "min drive" }, { name: "Amagansett", dist: "6", unit: "min drive" }] },
      { cat: "Connectivity", items: [{ name: "East Hampton Airport (HTO)", dist: "12", unit: "min drive" }, { name: "Midtown Manhattan", dist: "2.5", unit: "hrs drive" }, { name: "Helicopter (NYC)", dist: "35", unit: "min" }] },
    ],
    testimonials: [
      { text: "Shore Reserve is, simply, the finest residential product in the Hamptons. The architecture, the site, the quality of build — nothing else comes close.", name: "Richard & Emily Thornton", unit: "Home 4 · Purchased 2021" },
    ],
  },
  {
    id: "vantage-hill",
    name: "Vantage Hill",
    tagline: "Modern Masterpiece in Westchester",
    type: "Contemporary Residence",
    status: "Completed",
    location: "Westchester, New York",
    address: "Vantage Hill Road, Harrison, NY 10528",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2022",
    storeys: 2,
    units: 8,
    available: 0,
    availablePct: 0,
    architect: "Steven Holl Architects",
    interiors: "Vicente Wolf Associates",
    heroImg: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80", label: "Exterior" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=700&q=80", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Master Suite" },
      { src: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=400&q=75", label: "Pool" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=400&q=75", label: "Terrace" },
    ],
    description: [
      "Vantage Hill is a collection of 8 contemporary residences perched on a dramatic ridge in Harrison, Westchester — each offering unobstructed views across the Long Island Sound.",
      "Designed by Pritzker Prize winner Steven Holl, these homes represent some of the most architecturally significant residential work produced in the New York metro area in decades.",
      "All homes sold in 2022. Contact Meridian for resale opportunities."
    ],
    highlights: [{ num: "8", label: "Residences" }, { num: "100%", label: "Sold" }, { num: "2022", label: "Completed" }],
    floorPlans: [
      { key: "residence", label: "Hilltop Residence", floors: "Single-family, 2 storeys", interior: "6,400 ft²", terrace: "2,200 ft²", beds: "4", baths: "4.5", price: "Sold Out", available: "Resale Only", inclusions: ["Steven Holl architectural design", "Vicente Wolf interiors", "Sound views from every principal room", "Infinity pool facing the Sound", "3-car garage"] }
    ],
    amenities: [
      { icon: "◈", title: "Private Grounds", desc: "Each home set on 2–3 acres of private landscaped grounds." },
      { icon: "◆", title: "Gated Access", desc: "Private gated community with 24/7 security." },
      { icon: "✦", title: "Community Trail", desc: "Private trail network through the ridge with Sound viewpoints." },
    ],
    architect_quote: "Vantage Hill is about light — the way it moves across the Sound, the way it enters each room at every hour of the day. The architecture is designed around this phenomenon.",
    architect_name: "Steven Holl — Steven Holl Architects",
    designTeam: [
      { role: "Architecture", name: "Steven Holl Architects", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Vicente Wolf Associates", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "Scape Landscape Architecture", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Local", items: [{ name: "Harrison Town Centre", dist: "6", unit: "min drive" }, { name: "Rye Beach", dist: "10", unit: "min drive" }, { name: "Purchase Street", dist: "8", unit: "min drive" }] },
      { cat: "Connectivity", items: [{ name: "Harrison Metro-North", dist: "7", unit: "min drive" }, { name: "Midtown Manhattan", dist: "40", unit: "min train" }, { name: "Westchester Airport (HPN)", dist: "12", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "Steven Holl's architecture at Vantage Hill is transformative — we genuinely experience the light differently in this house than anywhere we've ever lived.", name: "Dr. Jonathan & Sara Mills", unit: "Residence 3 · Purchased 2022" },
    ],
  },
  {
    id: "the-solent",
    name: "The Solent",
    tagline: "LEED Platinum Living at Hudson Yards",
    type: "LEED Platinum Tower",
    status: "Completed",
    location: "Hudson Yards, New York",
    address: "55 Hudson Yards, NY 10001",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2021",
    storeys: 52,
    units: 88,
    available: 0,
    availablePct: 0,
    architect: "SOM — Skidmore, Owings & Merrill",
    interiors: "Clodagh Design",
    heroImg: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=900&q=80", label: "Tower Facade" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=700&q=80", label: "Building Lobby" },
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&q=75", label: "Primary Suite" },
      { src: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&q=75", label: "Hudson Views" },
      { src: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=75", label: "Terrace" },
    ],
    description: [
      "The Solent was the first LEED Platinum certified luxury residential tower in New York State — a 52-storey landmark at Hudson Yards that proved sustainable design and luxury living are not merely compatible, but mutually reinforcing.",
      "Designed by SOM with interiors by Clodagh Design, the building's passive systems, triple-glazed curtain wall, and rooftop energy infrastructure achieve a carbon footprint 60% below comparable towers without sacrificing a single square foot of amenity or finish quality.",
      "All 88 residences sold prior to completion. Resale enquiries to Meridian's secondary market team."
    ],
    highlights: [{ num: "88", label: "Residences" }, { num: "52", label: "Storeys" }, { num: "LEED", label: "Platinum Certified" }],
    floorPlans: [
      { key: "studio", label: "Studio+", floors: "Floors 8–20", interior: "890 ft²", terrace: "120 ft²", beds: "1", baths: "1", price: "Sold Out", available: "Resale Only", inclusions: ["Clodagh Design biophilic interiors", "LEED Platinum building systems", "Triple-glazed floor-to-ceiling windows", "Sustainable material palette", "Full building amenity access"] },
      { key: "two-bed", label: "Two Bedroom", floors: "Floors 21–38", interior: "1,980 ft²", terrace: "360 ft²", beds: "2", baths: "2", price: "Sold Out", available: "Resale Only", inclusions: ["Hudson River views", "Biophilic wall installations", "Sustainable stone and wood", "Smart building integration", "Private terrace"] },
      { key: "three-bed", label: "Three Bedroom+", floors: "Floors 39–52", interior: "3,200 ft²", terrace: "640 ft²", beds: "3+", baths: "3", price: "Sold Out", available: "Resale Only", inclusions: ["Panoramic Hudson and city views", "Full Clodagh design package", "Living wall feature", "Private study", "Wrap terrace"] }
    ],
    amenities: [
      { icon: "◈", title: "Living Lobby", desc: "A biophilic double-height lobby with living green walls and natural light wells." },
      { icon: "◆", title: "Wellness Floor", desc: "Full wellness floor with pool, gym, yoga studio, and spa — all powered by renewable energy." },
      { icon: "✦", title: "Rooftop Garden", desc: "Residents' rooftop garden with food production and city panoramas." },
      { icon: "▲", title: "EV Fleet", desc: "Shared electric vehicle fleet and fully equipped EV charging garage." },
      { icon: "●", title: "Co-Working", desc: "Private co-working suites and meeting rooms for resident use." },
      { icon: "◉", title: "Concierge", desc: "24/7 concierge and smart building management team." },
    ],
    architect_quote: "The Solent showed that the most responsible building and the most beautiful building can be one and the same thing.",
    architect_name: "SOM — Skidmore, Owings & Merrill",
    designTeam: [
      { role: "Architecture", name: "SOM — Skidmore, Owings & Merrill", firm: "New York / Chicago", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Clodagh Design", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Sustainability", name: "Thornton Tomasetti", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Hudson Yards", items: [{ name: "The Vessel", dist: "2", unit: "min walk" }, { name: "Hudson Yards Shops", dist: "3", unit: "min walk" }, { name: "The High Line", dist: "5", unit: "min walk" }] },
      { cat: "Transportation", items: [{ name: "7 Subway — Hudson Yards", dist: "2", unit: "min walk" }, { name: "Moynihan Train Hall", dist: "10", unit: "min walk" }, { name: "JFK Airport", dist: "35", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "Living in The Solent changed how I think about what a home can be. The sustainability is invisible in the best possible way — it just makes the building feel better to be in.", name: "Dr. Patricia Nguyen", unit: "Residence 4102 · Purchased 2021" },
    ],
  },
  {
    id: "the-rowan",
    name: "The Rowan",
    tagline: "The Landmark That Started It All",
    type: "Landmark Tower",
    status: "Completed",
    location: "Tribeca, New York",
    address: "12 Franklin Street, NY 10013",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2019",
    storeys: 42,
    units: 42,
    available: 0,
    availablePct: 0,
    architect: "Selldorf Architects",
    interiors: "Axel Vervoordt",
    heroImg: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80", label: "Tower Facade" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=700&q=80", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&q=75", label: "Terrace" },
      { src: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&q=75", label: "Exterior" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=75", label: "Primary Suite" },
    ],
    description: [
      "The Rowan was Meridian's first ground-up tower — and it set every standard that followed. 42 residences across 42 storeys, with Selldorf Architects' characteristically precise facade and Axel Vervoordt's warmly minimal interiors.",
      "The Rowan sold out in 11 days at launch — a record at the time for Tribeca — and went on to become one of the most resale-active buildings in the neighbourhood, consistently setting new price benchmarks.",
      "All residences are now in private ownership. Resale enquiries through Meridian's secondary market."
    ],
    highlights: [{ num: "42", label: "Residences" }, { num: "42", label: "Storeys" }, { num: "2019", label: "Completed" }],
    floorPlans: [
      { key: "two-bed", label: "Two Bedroom", floors: "Floors 6–26", interior: "2,100 ft²", terrace: "320 ft²", beds: "2", baths: "2.5", price: "Sold Out", available: "Resale Only", inclusions: ["Selldorf Architects design", "Axel Vervoordt interiors", "Limed oak and stone throughout", "Gaggenau kitchen", "Private terrace"] },
      { key: "three-bed", label: "Three Bedroom", floors: "Floors 27–38", interior: "3,400 ft²", terrace: "580 ft²", beds: "3", baths: "3.5", price: "Sold Out", available: "Resale Only", inclusions: ["Full Vervoordt interior specification", "Private study", "Wine storage", "Panoramic Tribeca views", "Large private terrace"] },
      { key: "penthouse", label: "Penthouse", floors: "Floors 39–42", interior: "6,200 ft²", terrace: "1,800 ft²", beds: "4", baths: "5", price: "Sold Out", available: "Resale Only", inclusions: ["Bespoke Vervoordt design", "Rooftop terrace", "Private elevator", "4-car parking", "Concierge floor"] }
    ],
    amenities: [
      { icon: "◈", title: "Residents' Lounge", desc: "Double-height lounge and library, available to all residents around the clock." },
      { icon: "◆", title: "Fitness Centre", desc: "State-of-the-art fitness centre and yoga studio on the 5th floor." },
      { icon: "✦", title: "Screening Room", desc: "Private 28-seat screening room with Dolby sound." },
      { icon: "▲", title: "Roof Terrace", desc: "Residents' rooftop terrace with Tribeca and Hudson River views." },
    ],
    architect_quote: "The Rowan is a building of considered restraint. Every decision — every setback, every material, every proportion — was made in service of the whole.",
    architect_name: "Annabelle Selldorf — Selldorf Architects",
    designTeam: [
      { role: "Architecture", name: "Selldorf Architects", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Axel Vervoordt", firm: "Antwerp / New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Structural Engineering", name: "DeSimone Consulting Engineers", firm: "New York", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Tribeca", items: [{ name: "Hudson River Park", dist: "4", unit: "min walk" }, { name: "Washington Market Park", dist: "3", unit: "min walk" }, { name: "Locanda Verde", dist: "2", unit: "min walk" }] },
      { cat: "Transportation", items: [{ name: "1 Subway — Franklin St", dist: "2", unit: "min walk" }, { name: "A/C/E — Canal St", dist: "5", unit: "min walk" }, { name: "JFK Airport", dist: "40", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "The Rowan has held its value better than anything else in Tribeca. We've had multiple unsolicited offers since we moved in — a testament to what Meridian built.", name: "Oliver & Claudia Hess", unit: "Residence 3101 · Purchased 2019" },
    ],
  },
  {
    id: "westover-estate",
    name: "Westover Estate",
    tagline: "Greenwich's First Great Community",
    type: "Estate Community",
    status: "Completed",
    location: "Greenwich, Connecticut",
    address: "Westover Lane, Greenwich, CT 06830",
    price: "Sold Out",
    priceRaw: "Sold Out",
    completion: "Completed 2018",
    storeys: 3,
    units: 22,
    available: 0,
    availablePct: 0,
    architect: "Peter Pennoyer Architects",
    interiors: "Tom Scheerer",
    heroImg: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1800&q=85",
    galleryImgs: [
      { src: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80", label: "Estate Facade" },
      { src: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=700&q=80", label: "Grounds" },
      { src: "https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=700&q=80", label: "Pool Terrace" },
      { src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&q=75", label: "Living Room" },
      { src: "https://images.unsplash.com/photo-1613977257592-4871e5fcd7c4?w=400&q=75", label: "Kitchen" },
      { src: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=75", label: "Primary Suite" },
    ],
    description: [
      "Westover Estate was Meridian's first major venture into the Connecticut luxury market — a community of 22 traditional estate homes in Greenwich's mid-country that set a new standard for the product available in the area.",
      "Designed by Peter Pennoyer with interiors by Tom Scheerer, the homes combine a deeply American architectural sensibility with the comfort and practicality demanded by today's buyers.",
      "Sold out in 2018. All homes are in private ownership. Contact Meridian for resale opportunities."
    ],
    highlights: [{ num: "22", label: "Estate Homes" }, { num: "100%", label: "Sold" }, { num: "2018", label: "Completed" }],
    floorPlans: [
      { key: "estate", label: "Estate Home", floors: "Single-family, 3 storeys", interior: "6,800 ft²", terrace: "2,600 ft²", beds: "5", baths: "5", price: "Sold Out", available: "Resale Only", inclusions: ["Peter Pennoyer traditional design", "Tom Scheerer interiors", "Pool and pool house", "3-car garage", "2-acre private lot"] }
    ],
    amenities: [
      { icon: "◈", title: "Community Club", desc: "Residents' clubhouse with dining room, lounge, and private events space." },
      { icon: "◆", title: "Tennis Courts", desc: "Three Har-Tru tennis courts for community use." },
      { icon: "✦", title: "Community Pool", desc: "Heated community pool and pool house, open seasonally." },
      { icon: "▲", title: "Gated Security", desc: "Private gated entry with 24/7 security and road maintenance." },
    ],
    architect_quote: "Westover Estate is architecture that aspires to feel inevitable — as though these houses have always been part of this landscape.",
    architect_name: "Peter Pennoyer — Peter Pennoyer Architects",
    designTeam: [
      { role: "Architecture", name: "Peter Pennoyer Architects", firm: "New York", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=75" },
      { role: "Interior Design", name: "Tom Scheerer", firm: "New York", img: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=200&q=75" },
      { role: "Landscape", name: "Innocenti & Webel", firm: "Locust Valley, NY", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=75" },
    ],
    designImg: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80",
    locationImg: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80",
    locationPins: [
      { cat: "Community", items: [{ name: "Greenwich Town Centre", dist: "10", unit: "min drive" }, { name: "Greenwich Country Club", dist: "6", unit: "min drive" }, { name: "Bruce Park", dist: "8", unit: "min drive" }] },
      { cat: "Connectivity", items: [{ name: "Greenwich Metro-North", dist: "12", unit: "min drive" }, { name: "Midtown Manhattan", dist: "45", unit: "min train" }, { name: "Westchester Airport (HPN)", dist: "22", unit: "min drive" }] },
    ],
    testimonials: [
      { text: "Westover Estate gave us exactly what we were looking for — the quality of a custom build, the ease of a managed community, and a neighbourhood of like-minded families. We couldn't be happier.", name: "Andrew & Fiona Carlisle", unit: "Estate 11 · Purchased 2017" },
    ],
  },
];
